### ISSUE TITLE
SEREN format IO for MPI

### ISSUE THREAD

**Issue by dhubber** [gandalfcode/gandalf#26]
Need to write routines for parallel MPI IO for SEREN format

**Comment by rbooth200** [comment]
This works properly for the unformatted format. Currently no other format is supported when MPI is used. I guess we can do without the column format when MPI is used, but are there any other formats that we should have? 

We should probably also check that the specified output format is sensible at setup.

**Comment by giovanni-rosotti** [comment]
So I never added the support for the formatted output/column format because it's a pain (you don't know in advance the length in bytes of what the processors before you are going to write) and it doesn't have real use cases (if you are using mpi, it's because it's a big simulation, so why would you want to use formatted output?), so it's not worth the effort.
If we do add HDF5 though, it obviously makes sense to make the MPI support it. It's possible that we don't even need to modify anything, as HDF5 is designed for parallel IO.

I do agree that the code should not let you run if the format is not sensible. Also, the userguide should report that with MPI you have a more limited choice of output formats.

**Comment by giovanni-rosotti** [comment]
See bd50019. I created a new branch for it to contain other error checking; feel free to commit there if you are aware of other clearly wrong combinations of parameters that should not be allowed. 
Btw, actually the column format does support MPI...

**Comment by giovanni-rosotti** [comment]
Contraddicting my previous statment, I will actually close this thread now and create a separate issue for HDF5
